# Generated by Django 3.2.5 on 2021-07-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210722_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='prep_time',
        ),
    ]
