# Generated by Django 3.2.5 on 2021-07-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipe_prep_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='post',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=1, upload_to='recipe_image'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RecipeImage',
        ),
    ]
