# Generated by Django 3.2.6 on 2021-08-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210727_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='title_ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='process',
            field=models.TextField(blank=True, null=True),
        ),
    ]
