# Generated by Django 3.2.5 on 2021-07-27 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210727_1324'),
        ('posts', '0003_alter_postimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
            preserve_default=False,
        ),
    ]
