# Generated by Django 3.2.5 on 2021-07-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='recipe',
        ),
    ]
